version: '2'
services:
  geoserver:
    build: ./geoserver
    stdin_open: true
    volumes:
    - /geoserver-data:/geoserver-data/data
    tty: true
    links:
    - postgres:postgres
    ports:
    - 33308:8080/tcp
  postgres:
    image: kartoza/haitidata_db:1.0
    environment:
      PASS: docker
      POSTGRES_PASS: docker
      POSTGRES_USER: docker
      USERNAME: docker
